/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/burguer.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.15, 0]} scale={[1.03, 0.74, 1.03]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['bread_outside._top.002']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.cheese} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.meat} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_6.geometry} material={materials.side} />
        <mesh geometry={nodes.Cylinder_7.geometry} material={materials.onion_top} />
        <mesh geometry={nodes.Cylinder_8.geometry} material={materials['bread_outside._top']} />
        <mesh geometry={nodes.Cylinder_9.geometry} material={materials.pit} />
      </group>
    </group>
  )
}

useGLTF.preload('/burguer.glb')
